export default [
  'free coding resources',
  'free javascript resources',
  'free coding tutorials',
  'tutorial javascript es6',
  'react tutorials',
  'full stack react tutorials',
  'learn react.js',
  'node js tutorials',
  'you dont know js',
  'learn redux',
  'learn GraphQL',
  'learn coding for free',
  'learn node js',
  'express js node resources',
  'javascript game development',
  'NYC Tech Pipline',
  'Free Code Camp',
  'NYC javascript meetups',
  'react native tutorial',
  'brooklyn.js',
  'nyc hackathon',
  '30 days of javascript',
  '100 days of code',
];
