export default [
  'free javascript resources',
  'tutorial javascript es6',
  'react tutorials',
  'full stack react tutorials',
  'node js tutorials',
  'afrotech',
  'learn redux',
  'learn coding for free',
  'learn node js',
  'javascript game development',
  'NYC Tech Pipeline',
  'Free Code Camp',
  'react native tutorial',
  'brooklyn.js',
  'nyc hackathon',
  'javascript weekly',
  '30 days of javascript',
  '100 days of code',
  'fullstack react',
  'frontendmasters',
  'typescript'
];
